export const LOCALITIES = [
  'Kpando Abanu (Main)',
  'Kpando Abanu (Quarters)',
  'Kpando Abgenoxoe',
  'Kpando Agudzi',
  'Kpando Aloyi',
  'Kpando Aloyi (Gboxome)',
  'Kpando Avetikofe',
  'Kpando Aziavi',
  'Kpando Bame',
  'Kpando BHECO',
  'Kpando Dafor',
  'Kpando Dzewoe',
  'Kpando Dzigbe',
  'Kpando Dzoanti',
  'Kpando Fesi (Atitsogse)',
  'Kpando Fesi (Avegah)',
  'Kpando Fesi (Debidibi)',
  'Kpando Fesi (Dzakpobi)',
  'Kpando Fesi (Kpene)',
  'Kpando Fesi (Quarters)',
  'Kpando Gadza',
  'Kpando Konda',
  'Kpando Todzi',
  'Kpando Torkor',
  'Kpando Togome',
  'Kpando Tsakpe (Asuto)',
  'Kpando Tsakpe (Avedza)',
  'Kpando Tsakpe (Dreveme)',
  'Kpando Tsakpe (Tsadome)',
  'Kpando Tsakpe (Hloma)',
  'Kpando Kpodzi',
  'Kpando Tsakpe (Newtown - First Stop)',
  'Kpando Tsakpe Newtwn - Old Assemb.',
  'Kpando Tsakpe (Newtown - Angola)',
  'Kpando Tsakpe (Newtown - Kpasae)',
  'Kpando Tsakpe (Newtown - Kpaenteh)',
  'Kpando Gabi',
  'Gbefi Hoeme',
  'Gbefi Tornu',
  'Sovie Abayeme',
  'Sovie Avenu',
  'Sovie Atsame',
  'Sovie Dzavlkame',
  'Sovie Konda',
  'Sovie Kudzra',
  'Sovie Nikorkordzi',
  'Sovie Nyamadzeanyi',
  'Sovie Tokoe',
  'Sovie Tsudzi',
  'Kpando Zongo',
] as const;

export const LOCALITY_AREA_CODE_MAP: Record<string, string> = {
  'Kpando Abanu (Main)': 'KpMA/KZC/ABM',
  'Kpando Abanu (Quarters)': 'KpMA/KZC/ABQ',
  'Kpando Abgenoxoe': 'KpMA/KZC/AGN',
  'Kpando Agudzi': 'KpMA/KZC/AGZ',
  'Kpando Aloyi': 'KpMA/KZC/ALY',
  'Kpando Aloyi (Gboxome)': 'KpMA/KZC/ALG',
  'Kpando Avetikofe': 'KpMA/KZC/AVK',
  'Kpando Aziavi': 'KpMA/KZC/AZV',
  'Kpando Bame': 'KpMA/KZC/BAM',
  'Kpando BHECO': 'KpMA/KZC/BHC',
  'Kpando Dafor': 'KpMA/KZC/DAF',
  'Kpando Dzewoe': 'KpMA/KZC/DZW',
  'Kpando Dzigbe': 'KpMA/KZC/DZG',
  'Kpando Dzoanti': 'KpMA/KZC/DZT',
  'Kpando Fesi (Atitsogse)': 'KpMA/KZC/FAG',
  'Kpando Fesi (Avegah)': 'KpMA/KZC/FAV',
  'Kpando Fesi (Debidibi)': 'KpMA/KZC/FDD',
  'Kpando Fesi (Dzakpobi)': 'KpMA/KZC/FDK',
  'Kpando Fesi (Kpene)': 'KpMA/KZC/FKM',
  'Kpando Fesi (Quarters)': 'KpMA/KZC/FQT',
  'Kpando Gadza': 'KpMA/KZC/GDZ',
  'Kpando Konda': 'KpMA/KZC/KDA',
  'Kpando Todzi': 'KpMA/KZC/TDZ',
  'Kpando Torkor': 'KpMA/KZC/TKR',
  'Kpando Togome': 'KpMA/KZC/TGM',
  'Kpando Tsakpe (Asuto)': 'KpMA/KZC/TAT',
  'Kpando Tsakpe (Avedza)': 'KpMA/KZC/TAV',
  'Kpando Tsakpe (Dreveme)': 'KpMA/KZC/TDV',
  'Kpando Tsakpe (Tsadome)': 'KpMA/KZC/TTD',
  'Kpando Tsakpe (Hloma)': 'KpMA/KZC/THM',
  'Kpando Kpodzi': 'KpMA/KZC/KDZ',
  'Kpando Tsakpe (Newtown - First Stop)': 'KpMA/KZC/TNF',
  'Kpando Tsakpe Newtwn - Old Assemb.': 'KpMA/KZC/TNO',
  'Kpando Tsakpe (Newtown - Angola)': 'KpMA/KZC/TNA',
  'Kpando Tsakpe (Newtown - Kpasae)': 'KpMA/KZC/TNK',
  'Kpando Tsakpe (Newtown - Kpaenteh)': 'KpMA/KZC/TNT',
  'Kpando Gabi': 'KpMA/KZC/GAB',
  'Gbefi Hoeme': 'KpMA/GZC/HME',
  'Gbefi Tornu': 'KpMA/GZC/TRN',
  'Sovie Abayeme': 'KpMA/SZC/ABM',
  'Sovie Avenu': 'KpMA/SZC/AVN',
  'Sovie Atsame': 'KpMA/SZC/ATM',
  'Sovie Dzavlkame': 'KpMA/SZC/DZM',
  'Sovie Konda': 'KpMA/SZC/KDA',
  'Sovie Kudzra': 'KpMA/SZC/KDZ',
  'Sovie Nikorkordzi': 'KpMA/SZC/NKD',
  'Sovie Nyamadzeanyi': 'KpMA/SZC/NDN',
  'Sovie Tokoe': 'KpMA/SZC/TKE',
  'Sovie Tsudzi': 'KpMA/SZC/TDZ',
  'Kpando Zongo': 'KpMA/KZC/ZNG',
};
