export const REVENUE_DESCRIPTIONS = [
  'Revenue',
  'Taxes',
  'Payable by individuals-Income Tax',
  'Pay As You Earn (PAYE) Tax',
  'Self Employed',
  'Vehicle Income Tax (VIT)',
  'Rent Income Tax',
  'Penalty- Individual',
  'Interest- Individual',
  'Property Tax',
  'Capital Gains Tax',
  'Capital Gains Tax Refund',
  'Withholding Tax - Residents',
  'Residents Dividend (8%)',
  'Fees to Teachers, Lecturers, Invigilators Examiners and Part-time Teachers (10%)',
  'Endorsement fees (10%)',
  'Payment for supply of goods or use of property or supply of services (Rent)',
  'Interest on the debt contracted for petroleum operations',
  'Commissions on Insurance Sales-Agent on Account',
  'Corporate Governance Fees on Account',
  'Interest on Account',
  'Lotto Commission',
  'Residential Rent Tax',
  'Non-Residential Rent Tax',
  'Lottery - Residents',
  'Rent paid for Non Residential Property- Individual (Investment Income 15%)',
  'Rent paid for  Residential Property- Individual (Investment Income 8%)',
  'Withholding Tax - Non Residents',
  'Short Term Insurance Premiums- Individual',
  'Dividend - Individual (8%)',
  'Royalties, Natural Resources payments and Rent- Individual',
  'Management, Consulting and Technical Service Fee and Endorsement- Individual (20%)',
  'Endorsement Fee- Individuals (20%)',
  'Goods, Works and services - Individual (8%)',
  'Incomes of Non Resident Entertainers- Individuals (20%)',
  'Transport Income - Individual',
  'Petroleum Subcontractor Final(Agreement)- Individual',
  'Interest on the debt contracted for petroleum operations',
  'Withholding Tax Refund - Individuals',
  'Non-Residential Rent Tax - Individual',
  'Residential Rent Tax- Individual',
  'Lottery - Non Residents- Individual',
  'Petroleum Subcontractor Final(statute)- Individual',
  'Telecommunication Service Income - Individual',
  'General Services Tax(payment for services)- Individual',
  'Withholding Tax on payment made for unprocessed precious minerals',
  'Withholding Tax - Non Residents with Permanent Establishment in Ghana',
  'Dividend',
  'Repatriation of branch profits to a non-resident person carrying on business through a permanent establishment',
  'Endorsements Management Technical Fees On Account',
  'Premiums Paid Non Resident Insurers On Account',
  'Royalties Natural Resource Payments Rents On Account',
  'Interest',
  'Payable by corporate and other enterprises',
  'Corporate Tax - Other Non Petroleum Companies',
  'Corporate Tax - Petroleum Companies',
  'State Enterprises',
  'Rent Tax',
  'Dividend Tax',
  'Commissions',
  'Tax Refund - Corporations',
  'Vehicle Income Tax (VIT)',
  'Penalty_Corporate Tax Standard',
  'Corporate Tax (Oil Lifting)',
  'Ineterest_Corporate Tax Standard',
  'Petroleum Companies',
  'Property Tax',
  'Capital Gains Tax',
  'Gift Tax',
  'Tax Refund - Corporations',
  'Withholding Tax - Corporate-Residents',
  'Residents Withholding Tax - Dividends',
  'Endorsement fees',
  'Payment for supply of goods or use of property or supply of services (Rent)',
  'Payment for supply of goods, works and services by Petroleum subcontractors for and in connection with a petroleum agreement',
  'Interest on the debt contracted for petroleum operations',
  'Commissions Insurance Sales Agents On Account',
  'Corporate Governance Fees On Account',
  'Interest On Account',
  'Lotto Commission',
  'Residential Rent Tax',
  'Non-Residential Rent Tax',
  'Education Fees Final-Company ( Fees to lecturers,invigilators, examiners, examination supervisors,part time teachers or lecturers (10%)',
  'Rent Paid for Non Residential Property (Investment Income- Company(15%)',
  'Rent paid to an individual Residential property( Investment Income  (8%)',
  '1% GCNET withholding tax',
  'Withholding Tax - Non Resident Corporations',
  'Short Term Insurance Premiums- Companies',
  'Dividend - Companies',
  'Royalties, Natural Resources payments and Rent- Companies',
  'Management, Consulting and Technical Service Fee and Endorsement- Companies',
  'Endorsement Fee- Companies',
  'Goods, Works and services - Companies',
  'Payments to a non-resident entertainer (L I 1675)',
  'Transport Income - Companies',
  'Petroleum Subcontractor Final(Statute)- Companies',
  'Petroleum Subcontractor Final(Agreement)- Companies',
  'Withholding Tax Refund - Corporations',
  'Residential Rent Tax - Companies',
  'Non-Residential Rent Tax - Companies',
  'Telecommunication Service Income - Companies',
  'General Services Tax(payment for services)- Companies',
  'Withholding Tax - Non Residents with Permanent Establishment in Ghana',
  'Dividend',
  'Repatriation of branch profits to a non-resident person carrying on business through a permanent establishment',
  'Withholding Tax Refund - Corporations',
  'Interest',
  'Miscellaneous',
  'Banderoles Tax',
  'Penalties-Unallocable',
  'Interest-Unallocable',
  'Ceded Miscellaneous Taxes',
  'Airport Tax',
  'Adhoc Levies',
  'Other Tax Refunds',
  'Environmental  Excise Tax',
  'Mineral Royalties',
  '1 Percent  CIF (GCNET)',
  'Unallocable_Registration Fees',
  'Taxes on property',
  'Basic Rates',
  'Property Rate Arrears',
  'Unassessed Rates',
  'Estate, inheritance, and gift taxes',
  'Estate, inheritance, and gift taxes',
  'Gift Tax',
  'General taxes on goods and services',
  'Value-added taxes - Standard Rate',
  'Agriculture, Fishing and Forestry',
  'Mining',
  'Manufacturing',
  'Utility Services including Electricity',
  'Construction',
  'Vehicles, Sales and Repairs',
  'Wholesale',
  'Retail',
  'Hotels and Restaurants',
  'Transport and Telecommunications',
  'Professional Services',
  'Recreational, Cultural and Sporting Activities',
  'Other Service Activities',
  'Financial and insurance activities',
  'Real estate activities',
  'Administrative and support service activities',
  'Public administration and defence; compulsory social security',
  'Education',
  'Human health and social work activities',
  'Activities of households as employers , undifferentiated goods- and services-producing activities of households for own use',
  'Activities of extraterritorial organizations and bodies',
  'Communication Service Tax',
  'Postal and courier activities',
  'Financial Service Charge',
  'FRS 1% COVID 19 LEVY',
  'NHIL 1% COVID 19 LEVY',
  'E-Levy',
  'Value-added taxes - Flat Rate',
  'Agriculture, Fishing and Forestry',
  'Mining',
  'Manufacturing',
  'Utility Services including Electricity',
  'Construction',
  'Vehicles, Sales and Repairs',
  'Wholesale',
  'Retail',
  'Hotels and Restaurants',
  'Transport and Telecommunications',
  'Professional Services',
  'Recreational, Cultural and Sporting Activities',
  'Other Service Activities',
  'Financial and insurance activities',
  'Real estate activities',
  'Administrative and support service activities',
  'Public administration and defence; compulsory social security',
  'Education',
  'Human health and social work activities',
  'Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use',
  'Activities of extraterritorial organizations and bodies',
  'Communication Service Tax',
  'Agriculture, Fishing & Forestry',
  'Value Added Taxes - Penalties',
  'Domestic VAT Penalty',
  'Domestic VAT Interest',
  'Domestic VAT',
  'NHIL',
  'Domestic NHIL - Standard Rate',
  'IMPORT NHIL',
  'Domestic NHIL Penalty',
  'Domestic NHIL Interest',
  'GET Fund Tax',
  'GET Fund Levy',
  'Import GET Fund Levy',
  'Communication Service Tax',
  'CST-Penalties',
  'CST-Interest',
  'Excises',
  'Domestic Excise Duty',
  'Amortization Fee - LPG',
  'Marine Gasoil- Foreign',
  'Gas Oil',
  'Residual fuel oil',
  'Jet Fuel (AT K)',
  'Kerosene',
  'L.P. Gas',
  'Petroleum Levy - Energy Fund',
  'Petroleum Levy - Exploration',
  'Petroleum Levy - Road Fund',
  'Petroleum - Strategic Stock Levy',
  'Petroleum Levy-Excise',
  'Promotional Levy - LPG',
  'Oil Industrial Diesel',
  'Unified Gasoline',
  'Petroleum - Cross Subsidy Levy',
  'Petroleum - Debt Recovery Levy',
  'Petroleum - Other Taxes',
  'Energy Debt Service Recovery Levy',
  'Price Stabilization & Recovery Levy',
  'Power Generation Infrastructure Levy.',
  'Pharmaceuticals',
  'Special Petroleum Tax',
  'Special Petroleum Tax',
  'Special petroleum Tax - Interest',
  'Special petroleum Tax - Penalties',
  'Foreign Exchange Under-recovery (Petroleum)',
  'SOC Impact Levy (Petroleum)',
  'Reschedule Payment (Petroleum)',
  'Penalty On Petroleum Payment (Petroleum)',
  'Power Generation Infrastructure Account',
  'TOR Debt Recovery',
  'Interest On Petroleum Payment',
  'Stock Fund Levy',
  'Penalty On Petroleum Payment (Petroleum)',
  'Taxes on specific services',
  'Casino Taxes',
  'Casino Taxes_Penalties',
  'Casino Taxes_Interest',
  'Customs and other import duties',
  'General Import Duties',
  'VAT on Imports',
  'Import Excise Duty',
  'Penalties on Import Duties',
  'Other Import Duties',
  'Import Inspection Fees',
  'Cassette Levy',
  'Rent Charges - State Warehouse',
  'Customs Penalties',
  'Customs Fines',
  'Customs - Forfeited Money',
  'Temporary Importation Fee',
  'Vehicle Examination',
  'Vehicle Certification',
  'Import Declaration Form',
  'Import Levies - Sensitive Commodities',
  'Ecowas Levy',
  'Export Development and Investment Fund Levy',
  'Manifest Amendment Fee',
  'Bonded Warehouse License Renewal',
  'TVI (C59) Fee',
  'Overtime Charges',
  'Vehicle Overage Penalty',
  'Import Exemption',
  'Special Import Levy 1%',
  'Special Import Levy 2%',
  'Special Petroleum Tax',
  'Custom Classification and Valuation Report Processing Fee',
  'African Union Import Levy',
  'EXIM Levy',
  'Penalty Miscellaneous',
  'Certification Fee',
  'Rent Warehouse',
  'Manufacturer License',
  'Manufacturer Renewal License',
  'Custom Inspection Fee',
  'Export Tax',
  'Mining Levy',
  'Special Import Tax',
  'Warehouse License Fee',
  'Tax Stamp- Soda Beer and Water',
  'Tax Stamp- Spirit and Wine',
  'COVID - 19 Health Recovery  Levy',
  'Network Charge COVID - 19 HEALTH',
  'Sanitation and Pollution Levy',
  'Energy Sector Recovery Levy',
  'Net Charge VAT',
  'Net Charge NHIL',
  'Net Charge GETFUND',
  'Anti-dumping Tax',
  'Temporary Vehicle Imports',
  'Saloon Cars',
  'Mini Bus - Bus Road Fund',
  'Non Articulated Trucks Road Fund - FD',
  'Articulated Trucks Road Fund',
  'TVI Extend Overstay Penalty',
  'TVI Close Overstay Penalty',
  'Importer Retention',
  'Processing Fee',
  'Auction Sales',
  'Official Publication',
  'Transit Administration Fee',
  'Taxes on exports',
  'Cocoa',
  'Timber',
  'Diamond',
  'Kola Nuts',
  'Re-Exports',
  'Other Export Duties',
  'Payable solely by business',
  'Payable solely by Corporate',
  'Stamp Duty',
  'Stamp Duty_Interest',
  'Stamp Duty_Penalties',
  'Payable solely by Individual',
  'Payable solely by Individual',
  'Stamp Duty',
  'Stamp Duty -  Interest',
  'Stamp Duty - Penalties',
  'NFSL',
  'NFSL - Penalties',
  'NFSL - Interest',
  'Grants',
  'External Source',
  'United Kingdom',
  'European Commission',
  'Switzerland',
  'Japan',
  'Canada',
  'Denmark',
  'France',
  'Africa Development Fund',
  'Germany',
  'International Government Association',
  'Kuwait Government',
  'Netherlands',
  'Spain',
  'United Development Programme',
  'United States Of America',
  'Counterpart Funds',
  'African Caribbean Pacific European Union',
  'World Bank',
  'Japanese NPT',
  'DANIDA',
  'European Union',
  'Africa Development Bank',
  'United Nations Development Program (UNDP)',
  'United Nation Children Education Fund (UNICEF)',
  'World Food Program (WFP)',
  'United Nation Population Fund (UNFPA)',
  'International Development Association',
  'Department For International Development (DfID)',
  'International Fund for Agric Development- IFAD',
  'International Private Organization',
  'Government of India',
  'United Nations Human Rights Commission (UNHCR)',
  'World Health Organization',
  'United States Agency for International Development (USAID)',
  'Govt. of Korea',
  'Arab Bank for Economic Devt.(BADEA)',
  'China',
  'Debt Restructuring Grant',
  'Domestic Non Governmental Agencies',
  'Non Governmental Agencies',
  'Other Government Agencies',
  'Central Government - GOG Paid Salaries',
  'DACF - Assembly',
  'DACF - MP',
  'Ceded Revenue',
  'HIPC',
  'Sanitation Fund',
  'National Youth Employment',
  'Other Donors Support Transfers',
  'Goods and Services- Decentralised Department',
  'DDF-Capacity Building Grant',
  'District Development Facility',
  'UDG Transfer Capital Development Project',
  'Sector Specific Asset Transfer Decentralised Department',
  'Korea Foundation For International Health (KOFIH)',
  'Ghana Education Trust Fund (GetFund)',
  'Non Tax Revenue',
  'Interest',
  'Petroleum - Participating Interest',
  'Interest on Re-scheduled debt - Customs',
  'Interest on GoG on-lent Loan',
  'Interest on loans/CAGD Loans Repayment',
  'Petroleum Tax Penalties',
  'Premium Issuance - Domestic Security',
  'Lands and Royalties',
  'Mineral Royalties',
  'Concessions',
  'Stool Land Revenue',
  'Development  and Building Permit Forms',
  'Comm. Mast Permit',
  'Additional Petroleum Entitlements',
  'Petroleum Royalties',
  'Development Fee ( State Lands)',
  'Income from Intellectual  Property',
  'Royalties',
  'Timber Royalty',
  'Other Inflows from Quasi Companies',
  'Net Income',
  'Property Rate',
  'Mineral Royalty-  Interest',
  'Mineral Royalty- Penalties',
  'Petroleum Royalty - Interest',
  'Petroleum Royalty - Penalties',
  'Participating Interest -  Interest',
  'Participating Interest - Penalties',
  'Property Rate Arrears',
  'Building Processing Charge',
  'Approval Fees For Land Application',
  'Change of Use Permit',
  'Rates',
  'Property Rate',
  'Basic Rate',
  'Special Rates',
  'General Rates',
  'Rates on other Possessions',
  'Development Levy',
  'Rents of Land, Buildings, Houses and Investment Incomes',
  'Concession Rent',
  'Ground Rent',
  'Petroleum Surface Rentals',
  'Rent, Oil Concessions',
  'Investment Income from Petroleum Funds',
  'Other Receipts from petroleum Operations',
  'Investment Income',
  'Dividend (Oil & Other Properties)',
  'Interest on Loans',
  'Other Investment Income',
  'Rent on Assembly Building',
  'Junior Staff Quarters',
  'Parks',
  'Club Houses',
  'Transit Quarters',
  'Educational Hall',
  'Farms Rents',
  'Free Zones Board Rent on Leased land',
  'Hiring of Facilities',
  'Mining Concession Rent',
  'Rental of Facilities',
  'Housing Rent',
  'Market and Stores Rental',
  'Craft shop',
  'Rent of Properties(Leasing)',
  'Housing Rent',
  'Leased Building',
  'Sales of Goods and Services',
  'Licenses',
  'Breweries/Distilleries',
  'Herbalist License',
  'Hawkers License',
  'Pet License',
  'Restaurant/Chop Bar/Caterers',
  'Corn / Rice / Flour Miller',
  'Liquor License',
  'Business Centers',
  'Bakers License',
  'Bicycle/Tricycle/Motorcycle Dealers',
  'Artisans',
  'Kiosk License',
  'Sand and Stone Dealers License',
  'Charcoal / Firewood Dealers',
  'Service/Filling Stations',
  'Lottery Business',
  'Hotel Services',
  'Pharmacy / Chemical Sellers',
  'Timber Products',
  'Commercial Vehicles',
  'Manufacturing/Processing Companies',
  'Canopy / Chairs / Bench',
  'Communication Services',
  'Private Education Int.',
  'Private Professionals',
  'Private Health Facilities',
  'Commercial Band / Dance Groups',
  'Private Security',
  'Mobile Sale Van',
  'Entertainment Services',
  'Wheel Trucks',
  'Akpeteshie / Spirit Sellers',
  'Stores',
  'Hand Carts',
  'District Weekly Lotto',
  'Petrochemical Companies',
  'Herbal Medicine',
  'Dress Makers/Tailor Services',
  'Bill Boards/Outdoor Advert',
  'Taxi Licenses',
  'Second Hand Clothing',
  'Vehicle Garage/Automobile Companies',
  'Financial Institutions',
  'Commercial Houses/Departmental Stores',
  'Advertising Companies',
  'Photographers and Video Operators',
  'Shoe / Sandals Repairs',
  'Fitters',
  'Mattress Makers / Repairers',
  'Millers',
  'Mechanics & Repairers',
  'Block And Concrete Products',
  'Cleaning/Laundry Services',
  'Printing Services / Photocopy',
  'Salt / Maize Sellers',
  'Private Schools',
  'Automobile Companies',
  'Cocoa Residue Dealers',
  'Airline  Agents',
  'Real Estate Agents',
  'Florists And Allied Products',
  'Public Letter Writers',
  'Alcoholic and non Alcoholic beverages',
  'Kola Nut dealers',
  'Private Recreational Parks',
  'Business Providers',
  'Contractor/Suppliers Registration',
  'Chain Saw Operator',
  'Drug Permit',
  'Permit',
  'Mining Operating License',
  'Digging Permit',
  'Prospecting/ Exploration  Permit',
  'Licensed Surveyors Reporting/Survey Data Fee',
  'Hunting License',
  'Free Zones Board License',
  'Free Zones Board Resident Permit',
  'Food and Drugs Permit',
  'Exporters of General Goods License',
  'Residence Permit',
  'Entry Permit/visa',
  'Permanent Residential Permit',
  'Burial Permit for Deceased Brought in from Abroad',
  'Chemical Clearance Permit',
  'Fish/Meat Clearance Permit',
  'Environmental Impact Analysis/Env. Mgt Plan',
  'Work Permit Fee',
  'Import permit',
  'Fishing Equipments License',
  'Restaurant License',
  'General Import and Export Services Providers',
  'Abattior',
  'Aluminum products',
  'Bridal House',
  'Butchers license',
  'Cold storage facilities',
  'Courier Services',
  'Customs Bonded Warehouse/Container Depot',
  'Drilling Companies',
  'Fish Farming',
  'Freight Forwarding',
  'Showrooms',
  'Funeral Homes/Mortuaries/Undertakers',
  'Job Placement Agency',
  'Landscapers/Horticulturists',
  'Market & Other Facilities Management Companies',
  'Non Governmental Institution',
  'Telecommunication Companies',
  'Transport Companies',
  'Transport unions',
  'Travel & Tour',
  'Treatment/ Storage Plant',
  'Bet & Game Centres License',
  'Veterinary License',
  'Online Trading',
  'Paper Product Companies',
  'Private meat van',
  'Publishing House',
  'wood fuel',
  'Refuse Container Managers',
  'Scrap Metal  Dealers',
  'Marketing Companies',
  'Gold Business',
  'Harbours',
  'Haulage Companies',
  'Film Production / Distribution',
  'Embossment/Embroidery Services',
  'Printing Services',
  'Electronic/Media Services',
  'Electrical Fencing Companies',
  'Hearse /Ambulance Service',
  'Self Employed',
  'Business License',
  'Sale of Building Permit Jacket',
  'Registration fee',
  'Transfer Fee',
  'Building Plans / Permit',
  'River Sand',
  'Comm. Mast Permit',
  'Game Viewing/Commercial TV Viewing Centres',
  'Slaughter License (Private)',
  'Art Gallery License',
  'Arts & Handicraft Dealers License',
  'Auctioning Firms/Agencies / Auctioneers License',
  'Arc/Argon (Aluminium)/Plastic Welders License',
  'Auto Upholstery License',
  'Vulcanisers License',
  'Barbering Shops (Floor space and number of points) License',
  'Sanitary Facilities - Private',
  'Agro Business Dealers License',
  'Bicycles/Tricycles/Motorcycles Parts Sales License',
  'Bicycle Tricycle/ Motorcycle Repairers  License',
  'Blacksmith License',
  'Boat/Canoe Operators License',
  'Bolt and Nut Dealers License',
  'Building Materials',
  'Building Material Dealers  Retail License',
  'Car Washing Bay License',
  'Carpentry and Joinrey Service License',
  'Casino and Slot Machines (Gaming) License',
  'Catering/School Feeding License',
  'CD Sellers (Audio/Video) License',
  'Cement & Limestone  Factories License',
  'Ceramics/Pottery Producers/Sellers  License',
  'Ceremonial Hiring Services',
  'Chandlery (shipping supplies) Services License',
  'Cigarette Dealers License',
  'Cocoa/ Shea Nut/Cotton Buying Companies License',
  'Coconut Oil Production/Sales License',
  'Coffee/Cashew  Buying Companies License',
  'Coffin Dealers License',
  'Cola Nut Dealers',
  'Commercialised State Companies/ Corporations  License',
  'Condiments/Confectioneries (e.g. Biscuits, toffees and spices) License',
  'Console (Consul) Games Operators License',
  'Cooking/Household Utensil Sales License',
  'Body Care Products License',
  'Curtains/Carpets etc. Sales License',
  'Dog License',
  'Dressmakers/Tailors (Industrial) License',
  'Dressmakers/Tailors (Non-Industrial) License',
  'Driving Schools Operational License',
  'Non-GES Regulated Institutions License',
  'Egg Dealers  License',
  'Electrical Appliances License',
  'Electrical Security Fencing Companies  License',
  'Electronic/Home Appliances/Shops  License',
  'Electronic/Home Appliance Parts Dealers License',
  'Electronic Media (Radio) Operators License',
  'Electronic Media (Television) Operators License',
  'Engineering Laboratories License',
  'Fabric  Dealers  Manufacturing  License',
  'Fabric  Dealers  Sales  License',
  'Financial Institutions (Non-Banking) License',
  'Fishing Nets and Accessories Dealers License',
  'Funeral  Undertakers License',
  'Furniture Showroom License',
  'General Goods - Sales (e.g. Generator, Water pump, Chain saw, etc.) License',
  'Gift Shops  License',
  'Glass Sellers (Tinted /Plain) License',
  'Graphic Design Companies License',
  'Hair & Beauty Service Providers  License',
  'Ice Cream/Yoghurt Dealers License',
  'Interior/Event Decorators License',
  'Jewellery Shops  License',
  'Jewellery Repairers (watches/bracelets, etc.) License',
  'Key Technicians/Cutters License',
  'Livestock Farms License',
  'Media Houses  License',
  'Medical Supply Companies License',
  'Mineral Water Manufacturing/Processing License',
  'Mineral Water Distribution/Sales  License',
  'Mineral Marketing Companies License',
  'Mining Sub-Contractors License',
  'Mobile Phone & Accessories Sales/Assembling/Repairs License',
  'Mobile Phone Cards Sales  License',
  'Musical  Instrument Sales  License',
  'Non-Governmental Institutions (Renewal)  License',
  'Palm/Kernel Oil Extraction Companies License',
  'Petrochemical Companies License',
  'Pharmaceutical Companies License',
  'Plastic Processing and Manufacturing Companies License',
  'Plastic Product Sales/ Water Tanks Suppliers License',
  'Plywood Manufacturers License',
  'Plywood Sellers License',
  'Poultry Farms License',
  'Energy Suppliers/Dealers',
  'Real Estate Operators License',
  'Recycling Plants/Companies License',
  'Rubber Stamp Makers License',
  'Safety Goods/Accessories (Workplace Related) License',
  'Safety Goods/Accessories (Health Related) License',
  'Shipping Companies License',
  'Signage Dealers',
  'Signage Writers License',
  'Software Development/ Software Support Companies License',
  'Solar Energy Dealers License',
  'Spare Parts Sales Outlets (New) License',
  'Spare Parts Sales Outlets(Second-hand)  License',
  'Straw Basket Weavers and Sales License',
  'Terrazzo Making License',
  'Tyre/Battery Dealers  New License',
  'Tyre/Battery Dealers  Used License',
  'Urinal Operators ( Private) License',
  'Utility Vendors License',
  'Vehicle - Private Examination Centres License',
  'Veterinary Clinic/Hospital License',
  'Warehouse (Private) License',
  'Windscreen Dealers License',
  'Automobile & Part Dealers',
  'Airline Offices/Operators',
  'Aluminium Pot Dealers (Dadesen)',
  'Boutiques',
  'Building Permit Renewal',
  'Temporary Structure Permit',
  'Change of Use Permit',
  'Aluminium Fabricators (Doors/Windows)',
  'Aluminium Products',
  'Bags and Suitcases Dealers',
  'Stationery and Office Supplies  Dealers',
  'Construction Artisans License',
  'Feed Sellers License',
  'Tourism Licensed Facilities',
  'Optical Services License',
  'Metal Fabricators',
  'Leather Works License',
  'CD Sellers (Audio/Video) License',
  'Waste Management Companies',
  'Beads Dealers',
  'Gas Cylinder/ Stoves & Accessory Dealers',
  'Grain Distributors',
  'Machine Shops (Workshop for making or repairing machines)',
  'Machine Sharpening Operators',
  'Rubber Cutting Machine Operators',
  'School Uniform',
  'Fees',
  'Markets Tolls',
  'Livestock / Kraals',
  'Sale of Poultry',
  'Registration /Renewal of Contractors',
  'Burial Fees',
  'Billboard/Signage Offences',
  'Export of Commodities',
  'Marriage Registration',
  'Sanitary Facilities',
  'Refuse Collection',
  'Dislodging Fees',
  'On-Street Parking Fees',
  'Industry Operations Fee',
  'Loading Fees',
  'Education Fees',
  'Professional Fees',
  'Wood Carving',
  'Chipping Const.',
  'Mineral Prospect',
  'Environmental Health Inspection & Certification Fee',
  'Consignment Transit Fee',
  'Aboticaba Fee',
  'Abstract Fee',
  'Academic Facility user Fee',
  'Accident Report Fee',
  'Academic Certificate',
  'Accommodation Fees',
  'Accreditation Fee',
  'Administrative charges',
  'Administrative Searches',
  'Admission Fee',
  'Adoption Fee',
  '5% Rent Refund',
  'Alien Registration',
  'Alteration in Death Register',
  'Alteration in Registering of Births',
  'Ambulance Fee',
  'Amendment of Bye-Laws',
  'Announcements Fee',
  'Apprenticeship Training Fee',
  'Approval of site plan',
  'Arms and Ammunitions',
  'Assaying',
  'Assignment Fee',
  'Attestation Fee',
  'Auction of Timber',
  'Auction Sales',
  'Auctioneers',
  'Audit Inspection',
  'Authentification Fee',
  'Attestation Fee',
  'Seedlings',
  'Badges',
  'Bailiff service Fee',
  'Mileage Claims',
  'User Fee (Domestic)',
  'Sale of Blood',
  'Service Fee',
  'Bond Form',
  'Boreholes Proceeds',
  'Bridge  and  Roads Tolls',
  'Change of Business Name',
  'Business registration',
  'C.T. Scan',
  'Cadastral Plans',
  'Third Party Deductions',
  'Camera Fee',
  'Camping Fee',
  'Capsid control (workshop charges spares and repairs)',
  'Vehicle Reflective Tape',
  'Vehicle Stickers for  Embossment',
  'Car towing',
  'Cardiology',
  'Care Passes',
  'Casino and Slot Machines (Gaming)',
  'Castration',
  'Catering services',
  'Certificate of Sale and Manufacturing',
  'Certification',
  'Chemical Regulation Certificates',
  'Chemistry Laboratory Services',
  'Cinnamon Seedlings',
  'Citizenship Registration',
  'Naturalisation',
  'Citrus seedlings',
  'Civil Service Examination Fee',
  'Clearance',
  'Medical Examination/treatment',
  'Clinical Trial',
  'Coconut Seedlings',
  'Cocoyam Fufu Powder',
  'Color Analyses',
  'Commercial Sales (Cereals)',
  'Commercial Sales (Maize)',
  'Commission on sales',
  'Commitment Fee',
  'Compost Bag',
  'Computer Maintenance Fee',
  'Conference Fee',
  'Conference Hall',
  'Confirmation Fee',
  'Confirmation of Results',
  'Consent (stool lands)',
  'Consent Fee- State Lands',
  'Consent Fee-State Lands',
  'Consent Fee-Stool Lands',
  'Consideration Fee',
  'Consular  Fee',
  'Consultancy Fee',
  'Consultation Fee',
  'Consumables',
  'Contractors registration Fee',
  'Corporate Training',
  'Course Fee',
  'Court Fee',
  'Criminal check',
  'Customary Fee',
  'Day Care Centre Fee',
  'Deeds Registration',
  'Delivery',
  'Demarcation',
  'Additional Qualification Fee',
  'Dental Fee',
  'Dept of Cooperatives Books',
  'Destination Inspection',
  'Destination Inspection of imported high risk goods',
  'Destruction Fee',
  'Advance Physician Assistants Retention Fee',
  'Deworming',
  'Diagnostic Centre',
  'Dialysis',
  'Documentary Examination',
  'Donation',
  'Vehicle Number Plate',
  'Dressing and Injections',
  'Drug Register',
  'Drug revenue earned',
  'Drugs (incl. Anaesthesia)',
  'Drying Fee',
  'Certification (B&D)',
  'Ear, Nose  and  Throat',
  'ECG  and  EEG',
  'Economic value',
  'ECOWAS Booklet',
  'Educational Programme',
  'Educational Visit',
  'Endorsement',
  'Enrolment Fee',
  'Entrance Fee',
  'Establishment of Industries',
  'Examination Fee',
  'Exhibition/Trade Fee',
  'Exhibition Hall Bookings',
  'Exhumation  and  Reburial',
  'Exportation of Remains',
  'Exporters Registration Fee',
  'Advance Retention',
  'Eye Care',
  'F.B.D. Processing Fee',
  'Fair Participation Fee',
  'Family Planning',
  'Fee for Courses and Certificates',
  'User Fee (Foreign)',
  'Feeding Fee',
  'Alumni Dues',
  'Fermented Maize Meal',
  'Ferry Tolls',
  'Filing Fee',
  'Finger Prints Analysis/ Employment',
  'Fingerprint Analysis (non Residents)',
  'Fingerprint Analysis (Residents)',
  'Fire Arms',
  'Fire safety Education',
  'Fish Levy(Import Export)',
  'Fishing Licensing Fee',
  'Flood Lights Charges',
  'Documents Charge',
  'Administration Charges',
  'Food and drug board Advertisement Fee',
  'Food and drug board Application Fee',
  'Food and drug board Registration Fee',
  'Form 9 ( Port to FZ )',
  'Form 9A ( Local Mkt )',
  'Form 9B ( VAT Exempt )',
  'Form 9E',
  'Form 9F',
  'Fabrication',
  'Free Zones Board Application Forms',
  'Amendment Fee',
  'Fresh Nut Bunches',
  'Fruit Training',
  'Fund raising and Fee',
  'Advertisement Fee',
  'G.N.A. Advertisement',
  'G.N.A. Subscription Fee',
  'Game  License',
  'Garage Jobs',
  'Gate Proceeds',
  'General Chemistry',
  'General Maintenance  Fee',
  'General Register',
  'Geological Survey Auction Sales',
  'Germinated Seed Nuts',
  'Amendment of Records (Change of Name)',
  'Ghana Highways Lab Tests',
  'Ghana Investment Promotion Centre Exemption Fee',
  'Ghana Investment Promotion Centre Registration',
  'Amendment of Records (Change of Date)',
  'Ghana Tourism Authority Registration Forms',
  'Ghana tourism authority Registration(Project)',
  'GHARR 1 centre Service Fee-NNRI',
  'Groundnut Paste',
  'Guard Duties',
  'Guest House',
  'Guest Application of HND (Pharmacy Technician) and Other Pharmacy Related Programsouse Services',
  'Guide and Transport Fee',
  'Gymnasium Fee',
  'Aptitude Test Fee',
  'Hawkers Fee',
  'Health centres Accommodation',
  'Health centres Laboratory',
  'Hiring of Vehicles/moveable properties',
  'Hire of Canopies',
  'Hire of Ferries  and  River Crafts',
  'Hire of Land and Equipment - Service',
  'Hire of Plastic Chairs',
  'Hire of Transport',
  'Human resource Development Fee',
  'Immigration Fee',
  'Importers Fee',
  'Indentures Fee',
  'Indexing Fee',
  'Attachment Registration Fee',
  'Calibration Fee',
  'International Standard Book Number',
  'Interview Fee',
  'Investigation Report',
  'Irrigation Service',
  'Carpentry and Joinrey Services',
  'Issue of certificates',
  'Carrier Liabilty Penalty',
  'Laboratory Fee',
  'Land Preparation',
  'Land Title Search  Fee',
  'Lease Preparation',
  'Legal Fee',
  'Library Fee',
  'License Duties',
  'License to Store Explosives',
  'Licensure Exams Fee',
  'Manufacturing License',
  'Map sales (Hard and Digital copy)',
  'Mastercraftmanship',
  'Matriculation Fee',
  'Medical charges',
  'Medicines  and  Pharmaceuticals',
  'Microbiological',
  'Change fees',
  'Mortuary Fee',
  'Residential & Academic User Fee',
  'Non Timber Forest Produce',
  'Training Fee',
  'Oath Fee',
  'Obstetrics and Gynaecology Fee',
  'OPD Fee',
  'Open Market value',
  'Ophthalmology',
  'Packaging Amendment',
  'Palm Oil Export',
  'Passport Fee',
  'Passport Forms Operational',
  'Pattern Approval',
  'Paediatrics',
  'Photocopies',
  'Physiotherapy',
  'Planning Development Fee-NVTI',
  'Plotting',
  'Police Escort Charges',
  'Police Reports',
  'Post Mortem',
  'Premium',
  'Preparation Fee',
  'Presentaion Fees',
  'Prison farms',
  'Prison Industries',
  'Prison Labour',
  'Proceeds from internet facilities',
  'Processing  and Storage',
  'Processing Fee',
  'Promotional Fee',
  'Sale of LD Plans',
  'Quarry/Restricted',
  'Quota Fee',
  'Radiology Services',
  'Raw Water Charges',
  'Analysis Fee',
  'Re-entry visa Fee',
  'Registration Fee',
  'Registration Form',
  'Registration of Estate',
  'Registration of Names/partnerships',
  'Registration of NGO\'s',
  'Registration of Patent/Textiles/Trade marks',
  'Registration of Political Parties',
  'Registration/Renewal of Firearms',
  'Regularisation Fee',
  'Regulatory Inspection Test',
  'Reimbursement of Audit Expenses By the United Nations',
  'Religious Bodies Registration',
  'Renewal of License',
  'Replacement of certificate',
  'Re-registration Fee',
  'Research Fee',
  'Sale of Airtime',
  'Sale of Animals /Plant Produce',
  'Sale of Blacksoil/Manure/Compost',
  'Sale of Educ. Materials',
  'Sale of Forms',
  'Sale of tuber products',
  'Sale of Geological Maps',
  'Sale of Grass',
  'Sale of Hansard',
  'Sale of Health Forms',
  'Sale of Highway Code',
  'Sale of ID cards/ID Card Fee',
  'Sale of Liquid Nitrogen',
  'Change of Pharmacist',
  'Sale of Meteo Data',
  'Sale of National Biography',
  'Sale of Personal Identification Number',
  'Sale of Plants',
  'Sale of Products',
  'Sale of Publication',
  'Sale of Publications Translation Work',
  'Sale of Seeds',
  'Sale of Standards to Producers,Importers  and  Exporters',
  'Sale of Unserviceable Scrap',
  'Sale of Vaccine',
  'Sale of Value Books',
  'Sale of Vegetables',
  'Sale of Wreaths/Bouquets',
  'Sales of Insecticide',
  'Sales of Livestock  and  Feeds',
  'Sanitation Charges',
  'Schedule Form B',
  'School Fee',
  'Approval Fee',
  'Transaction Levy',
  'Seminar Hall',
  'Semester  Exams Registration',
  'Semester Exams Fee',
  'Sensory Evaluation',
  'Service Charge',
  'Shift Boss/Mine Foreman Certificate Examination',
  'Short Course Fee',
  'Short Guide',
  'Sample Analysis Fee',
  'Sports and  Entertainment',
  'Sports and Culture Fee',
  'Sports Dev\'t/Manufacturing Services-NSS',
  'Sports Levy',
  'SRC Dues',
  'Continuous Education',
  'Stationery Fees',
  'Course Material Fee',
  'Stumpage',
  'Subscriptions',
  'Sundry Fee (Inspections, reg. and cert. of Sch)',
  'Surgery Fee',
  'Surgical Fee',
  'Survey Fee',
  'Sale of Textbooks',
  'Technology Transfer Fee',
  'Tender Documents',
  'Development Levy',
  'Testing Fee',
  'Theatre Charges',
  'Tour/Camera Fee',
  'Tractor Services',
  'Trade marks',
  'Trainees Contributions',
  'Training  and  W\'shops Including international standards organisation 9000 QMS',
  'Training Centres',
  'Training Pitches User Fee',
  'Training Fee',
  'Transfers  and  Change of Ownership',
  'Transport Fee',
  'Tuition Fee',
  'License Fee',
  'User Fee ( Domestic)',
  'Valuation Fee',
  'Variation Fee',
  'Vehicle Clearance Form',
  'Vehicle Roadworthiness Certificate',
  'Verification Fee',
  'Vested Lands',
  'Veterinary Clinic  Service Fee',
  'Vetting Fee',
  'Visa Fee',
  'Scratch Card',
  'ID Cards',
  'Winding Engine',
  'Disposal of Assets',
  'Distance Education Students Fee',
  'Workshop',
  'X-Ray',
  'Public Visits',
  'Affiliation fee',
  'Arts School',
  'Sale of Art Works',
  'Laboratory Diagnostic Test',
  'Sale of  Milk',
  'Sale of  Milled Animal Feed',
  'Finger Print Analyses',
  'Police Report',
  'Crime Lab',
  'Registration of Birth',
  'Late Change of Birth Date',
  'Cancellation Of Multiple Reg.',
  'Incoming International Telephone Traffic Wiremax',
  'Register Books',
  'Tourist Map',
  'Informal Plants',
  'Bidding Documents',
  'Rope Test',
  'NITA Services',
  'Active Directory Services',
  'Antivirus Services',
  'Internet Services',
  'Windows Update Services',
  'E-Mail Services',
  'Co-Location Services',
  'Wide Area Network',
  'Storage and Backup Services',
  'Domain Registration',
  'Web Hosting',
  'Travel Certificate',
  'Landscaping',
  'Plotted Plant',
  'Classification Fees',
  'Road Specification Document',
  'Citizenship Renunciation Fee',
  'Sale of law reports',
  'Sale of audio visual lessons on VCD/DVD',
  'Sales of souvenirs',
  'Sale of Fuel',
  'Standard Development',
  'Sale of Statutory Documents',
  'Sale of vaccines',
  'Confiscated  Assets',
  'Depository fees',
  'FUEL LEVY',
  'Bridge/Road Tolls',
  'Percentage charge on consultancy fees',
  'Labour Tender Certificate',
  'Tourism License',
  'Examination fees',
  '3% Administration Charge',
  'Membership and Fellowship Dues',
  'Certificate and Log Books',
  'Medical Knowledge Fiesta',
  'Certification Fee',
  'Dispute Settlement Fees',
  'Application & license Fees',
  'Hawkers Fees',
  'Registration and Licensure',
  'Professional Identification Number (PIN)',
  'Auxiliary Identification Number (AIN) Renewal Fee',
  'Foreign Trained Examination Fee',
  'Foreign Verification Fee',
  'Local Verification Fee',
  'Academic User Fees (Mandatory & Certificates).',
  'Application Fees',
  'Production Fees',
  'Graduation Fees',
  'Transcript & Recom. Fee',
  'Library Fines',
  'Matriculation Fees',
  'Share of Net Gate proceeds for League Matches.',
  'Stadium Adverts',
  'Community Health Nursing Exams Fees.',
  'Health Assistant (Clinical) Exams Fees.',
  'Registration and Consignment Fees for Precursor Chemicals',
  'Precursor Charges',
  'Registered General Nursing Exams Fees.',
  'Registered Midwifery Exams Fees.',
  'Registered Mental Nursing Exams Fees.',
  'Registered Community Nursing Exams Fees.',
  'Midwifery (Post Basic) Exams Fees.',
  'Public Health Nursing Exams Fees.',
  'Ophthalmic Exams Fees.',
  'Peri-Operative/Critical Care Exams Fees.',
  'Registration of Local Manufactures',
  'Processing Fees',
  'Consideration Fees',
  'Search fees',
  'Publication fees',
  'Exemption Fees',
  'Re- labelling coc/coa Fee',
  'Calibration of Hospital Instruments',
  'Histopathology Fee',
  'Entrance Fees',
  'Camera/Filming Fee',
  'Museums /Monuments  Fee',
  'Commonwealth Law Drafting',
  'Transcript & Recommendation Letter',
  'Penalty- GSA Certification Mark',
  'Verification and Calibration Fee',
  'Verification of Weighing Scales',
  'Auction / Disposal Fees',
  'Fish and Fishery Products',
  'Weighbridge Project',
  'Fuel Instrument Verification',
  'Flow Measurement/Meters',
  'Quality Management System Certification',
  'Library Subscription',
  'Survey Services/Works',
  'Composite Plans',
  'Site Plan Drawings',
  'Consent State  -Lands Commission',
  'Premium  -Lands Commission',
  'Concurrence  -Lands Commission',
  'Deeds registration  -Lands Commission',
  'Mobilization  -Lands Commission',
  'Check/Approval  -Lands Commission',
  'Regional No.  -Lands Commission',
  'Construction Works',
  'Prison Labour',
  'Processing Fees -Lands Commission',
  'Plotting Fees  -Lands Commission',
  'Certified True Copy  -Lands Commission',
  'Permit/Development Application',
  'Postage Fee',
  'Presentation Fees',
  'Concession Rate',
  'Monitoring Fees',
  'Underground Fuel Tanks',
  'Application forms',
  'Appeal /Bail Fees',
  'SUB-District Support',
  'Continuous Professional Devt.',
  'Charcoal / Firewood Dealers',
  'Business  /product promotion',
  'Assembly\'s Meat Van',
  'Warehouse Charges',
  'Approved Transfers of Stall & stores',
  'Off Loading/ Landing Fee',
  'Reclamation fees',
  'ICU- Charges',
  'Intramural Services',
  'Sale of Prosthetics (Implant)',
  'Endoscopy',
  'Sale of Oxygen',
  'Blank Levy',
  'Sale of Water',
  'Connection Fee',
  'Road Accident Levy',
  'Slaughter Fees (Private)',
  'Cremation Fees',
  'Mausoleum Fees',
  'Exhumation of Corpse  Fees',
  'Calibration of Noise Emission Fees',
  'Operated Public Toilet/Urinal/Bathhouse Fees',
  'Crusade Outreach /Concert Programmes Fees',
  'Environmental Health Inspection and Certification Fees',
  'Export/Conveyance Fees',
  'Lorry Park Fees',
  'Spinster/ Bachelor Certificate Fees',
  'Waste Management Companies',
  'Special Registration Fee',
  'Road Block  Fees',
  'Land Application Fees',
  'CD Sellers (Audio/Video) Fees',
  'Bitcher\'s Fee',
  'Tendering Fees',
  'ICT Centre Operations (Assembly?s)',
  'Export Levy',
  'Official Liquidation Fees',
  'Fees for Professional Bodies',
  'Companies Bulleting',
  'Meager and Acquisition Fee',
  'Bulk Data on Businesses fees',
  'Fines, penalties, and forfeits',
  'Court Fines',
  'Miscellaneous Fines, Penalties',
  'Slaughter Fines',
  'Lorry Park Fines',
  'Auction Sales',
  'Penalty',
  'Fines',
  'Spot fine',
  'Confiscated Assets',
  'Seizures',
  'Traffic Offences',
  'Impounding Fines',
  'Building Offences',
  'Unauthorised Diversion',
  'Retrieval of Seized Tools',
  'Environmental Health/Safety/Sanitation Offences',
  'Building Without Permit Fines',
  'Illegal/Un-Licensed Activities',
  'Unauthorised Structures Fines',
  'Refurbishment/ Renovation without Permit Fines',
  'Environmental Abuse Offences Fines',
  'Stray Animals Fines',
  'General Negligence Related Fines',
  'Miscellaneous Non tax revenue',
  'Non-Performing Assets Recoveries',
  'Divestiture Receipts',
  'Subsidies Repayments',
  'Recoveries of Overpayments in Previous years',
  'Recoveries Under Various Statutes',
  'Redemption of Other Loans And Advances',
  'Other Sundry Recoveries',
  'Reimbursement',
  'District/Regional Treasury Collections',
  'Stabilization Revenue',
  'Loan Recovery',
  'Refund & Credit Balance',
  'Sponsorship (Film TV Festival)/GBC',
  'Sponsorship (Film TV Festival)/GBC',
  'Interest Income (Bank Interest)',
  'SSNIT 2 1/2  Percent',
  'Special Collection EUR',
  'Special Collection GBP',
  'Special Collection USD',
  'Exchange Gain',
  'Service Concession Revenue',
  'Unretain IGF',
  'Profit/ Loss on Disposal',
  'Profit/ Loss on Disposal_Land',
  'Profit/ Loss on Disposal_Building and Structures',
  'Profit/ Loss on Disposal_Office Equipment/ F&F',
  'Profit/ Loss on Disposal_ICT Equipment',
  'Profit/ Loss on Disposal_Other Machinery and Equipment',
  'Profit/ Loss on Disposal_Infrastructure Assets',
  'Profit/ Loss on Disposal_Transport Equipment',
  'Profit/ Loss on Fair Value of Financial Assets',
  'Profit/ Loss on Fair Value of Non-Financial Assets',
  'Notional Revenue',
  'Domestic NHIL Notional Revenue',
  'Petroleum, Energy and Road Fund',
  'NHIL- Import and SSNIT Notional',
  'GIIF-Ghana Infrastructure Investment Fund',
  'Energy Sector Levy Notional Revenue',
  'Expense',
  'Compensation of Employees [GFS]',
  'Established Post',
  'Established Post',
  'Non Established Post',
  'Daily Rated',
  'Monthly Paid and Casual Labour',
  'Probation',
  'Recruitment',
  'Secondment',
  'Limited Engagements',
  'Other Allowances',
  'Motorbike Allowance',
  'Bicycle Maintenance Allowance',
  'Car Maintenance Allowance',
  'Bereavement Allowance',
  'Book Subsidy',
  'Committee of Council Allowance',
  'Continuous Judicial Education Allowance',
  'Funeral Grants',
  'Journalist Allowance',
  'Jurors Allowance',
  'Commuted Leave Allowance',
  'Watchman Allowance',
  'Protocol Commission',
  'Rations',
  'Rotational Head of Department Allowance',
  'Rules of Council Allowance',
  'Rules of Court Allowance',
  'Steering Committee Allowance',
  'Top-Up Allowance',
  'Training Allowance',
  'Watchman Extra Days Allowance',
  'Basic PE Related Allowances',
  'Traditional Authority Allowance',
  'Boards /Committees Allowance',
  'Duty Allowance',
  'Clothing Allowance',
  'Acting Allowance',
  'Cashier Allowance',
  'Commissions Meeting Allowances',
  'Professional Allowance',
  'Entertainment Allowance',
  'Fuel Allowance',
  'Guide Allowance',
  'Housing Subsidy/Allowance',
  'Risk Allowance',
  'Overtime Allowance',
  'Tools Allowance',
  'Uniform and Protective Clothing Allowance',
  'Per Diem and Inconvenience Allowance',
  'Travel Allowance',
  'Transfer Grants',
  'Out of Station Allowance',
  'Domestic Servants Allowance',
  'Foreign Service Allowance',
  'Utility Allowance',
  'Special Allowance/Honorarium',
  'Responsibility Allowance',
  'Child Allowance',
  'Cost of Living Allowance (COLA)',
  'ISO Allowance',
  'IT Allowance',
  'Management Furnishing',
  'Market Premium',
  'Disability Premium',
  'Compensatory Allowance',
  'Height Allowance',
  'Child Education Grant (Foreign Mission)',
  'Part time Allowance',
  'Research Allowance',
  'Invigilation Allowance',
  'Compensation Arrears',
  'Established Post Arrears',
  'Non Established Post Arrears',
  'Allowances Arrears',
  'Wages and Salaries in Kind [GFS]',
  'Child Allowance',
  'Cost of Living Allowance (COLA)',
  'Social Contributions [GFS]',
  'Actual Social Contributions ( National Pension Contribution )',
  '13 Percent  SSF Contribution',
  'Gratuity',
  'Pension',
  'End of Service Benefit (ESB/Ex-Gratia)',
  'Superannuation',
  'Imputed Social Contributions [GFS]',
  'Non-Salary Related Allowance Control',
  'Use of Goods and Services',
  'Materials and Office Consumables',
  'Printed Material and Stationery',
  'Office Facilities, Supplies and Accessories',
  'Refreshment Items',
  'Medical Supplies',
  'Drugs',
  'Oils and Lubricants',
  'Electrical Accessories',
  'Construction Material',
  'Spare Parts',
  'Specialised Stock',
  'Other Office Materials and Consumables',
  'Uniform and Protective Clothing',
  'Feeding Cost',
  'Rations',
  'Textbooks and Library Books',
  'Chemicals and Consumables',
  'Teaching and Learning Materials',
  'Sports, Recreational and Cultural Materials',
  'Household Items',
  'Purchase of Petty Tools/Implements',
  'Clothing and Uniform',
  'Value Books',
  'Utilities',
  'Electricity charges',
  'Water',
  'Telecommunications',
  'Postal Charges',
  'Sanitation Charges',
  'Armed Guard and Security',
  'Fire Fighting Accessories',
  'Gas and Heating',
  'General Cleaning',
  'Cleaning Materials',
  'Contract Cleaning Service Charges',
  'Rentals/Lease',
  'Office Accommodations',
  'Residential Accommodations',
  'Rental of Office Equipment',
  'Hotel Accommodations',
  'Rental of Land and Buildings',
  'Rental of Vehicles',
  'Rental of Other Transport',
  'Rental of Furniture and Fittings',
  'Rental of Plant and Equipment',
  'Rentals of Computers and Accessories',
  'Rental of Network and ICT Equipments',
  'Rental of Towing Vehicle',
  'Lease of Communication Gadgets',
  'Lease of Vehicle',
  'Lease of office equipments',
  'Lease of office building',
  'Lease of Land',
  'Lease of Plant and Equipment',
  'Travel and Transport',
  'Overseas Medical Treatments',
  'Maintenance and Repairs - Official Vehicles',
  'Fuel and Lubricants - Official Vehicles',
  'Car Rental/Leasing',
  'Running Cost - Official Vehicles',
  'Freight and Handling Charges',
  'Running Cost of Presidential Aircraft',
  'Running Cost of Fighting Vehicles',
  'Other Travel and Transportation',
  'Other Night allowances',
  'Local travel cost',
  'Mileage Allowance',
  'Local Hotel Accommodation',
  'Foreign Travel- Per Diem',
  'Foreign Travel Cost and Expenses',
  'Toll Charges and Tickets',
  'Fuel Allocation To Waste Management Department',
  'Vehicle Registration',
  'Repairs and Maintenance',
  'Roads, Driveways and Grounds',
  'Repairs of Residential Buildings',
  'Repairs of Office Buildings',
  'Maintenance of Furniture and Fixtures',
  'Maintenance of Machinery and Plant',
  'Maintenance of General Equipment',
  'Repairs of Schools/Colleges',
  'Maintenance of  Aircraft',
  'Maintenance of Fighting Vehicles',
  'Maintenance of Drains',
  'Maintenance of Markets',
  'Maintenance of Public Toilet/Urinals/Bath Houses',
  'Traditional Authority Property',
  'Recreational Parks',
  'Maintenance of Public Sanitary Facilities',
  'Street Lights/Traffic Lights',
  'Maintenance of Cemeteries',
  'Repair of Elevator(Lift)',
  'Security Gadgets',
  'Maintenance of Computer Software',
  'Maintenance of Office Equipment',
  'Training, Seminar and Conference Cost',
  'Training Materials',
  'Seminars/Conferences/Workshops/Meetings Expenses -Foreign',
  'Examination Fees and Expenses',
  'Hire of Venue',
  'Hotel Accommodation',
  'Library and Subscription',
  'Recruitment Expenses',
  'Refreshments',
  'Seminars/Conferences/Workshops - Domestic',
  'Staff Development',
  'Public Education and Sensitization',
  'Consultancy Expenses',
  'Local Consultants Fees (Companies)',
  'External Consultants Fees',
  'Other Consultancy Expenses',
  'Contract appointments',
  'Consultants Materials and Consumables',
  'Local Consultants Commission (Individuals)',
  'Special Services',
  'Service of the State Protocol',
  'Official Celebrations',
  'Head of State End of Year Activities',
  'Substructure Allowances',
  'Assembly Members Sittings All',
  'Unit Committee/T. C. M. Allow',
  'Canteen Services',
  'Property Valuation Expenses',
  'Operational Enhancement Expenses',
  'Trade Promotion / Publicity',
  'Other Charges and Fees',
  'Bank Charges',
  'Bank Errors',
  'Audit Fees',
  'Exchange Loss',
  'Rounding',
  'NHIL - Penalties',
  'NHIL - Interest',
  'Arrangement Fee on Loans',
  'Participation Fee on Loans',
  'Medical Claims- Services',
  'Medical Claims- Medicines',
  'Emergency Services',
  'Field Operations',
  'Refurbishment Contingency',
  'Emergency Works',
  'Security Forces Contingency (Election)',
  'Insurance Premium',
  'Insurance of Residential Accommodation',
  'Insurance of Office Accommodation',
  'Insurance of Property, Plant and Equipment',
  'Insurance of Vehicles',
  'Owners Liability',
  'Rate Variance Gain/Loss',
  'Rate Variance Gain/Loss',
  'Consumption of fixed capital [GFS]',
  'Depreciation',
  'Provision for Bad Debt',
  'Provision for Bad Debt Loans',
  'Provision for Bad Debt Investments',
  'Interest [GFS]',
  'Non-Residents',
  'External Interest Payment',
  'External Statutory Payment-Principal',
  'Residents Other than General Government',
  'Internal Interest Payment',
  'Internal Statutory Payments - Redemption',
  'Other Interest',
  'Interest On Overdraft',
  'General Government Units',
  'Government Units',
  'Subsidies',
  'Public Corporations Entities',
  'Non-Financial Public Corporations',
  'To Financial Public Corporations',
  'Financial Public Corporations',
  'Oil Subsidy',
  'Utility Subsidy',
  'Capitation Grants',
  'Schools Subsidy( BECE and SHS)',
  'Feeding Grant',
  'Fertilizer Subsidy',
  'District/Regional Support',
  'Private Entities',
  'Non-Financial Private Enterprises',
  'Financial Private Enterprises',
  'Grants',
  'Foreign Governments',
  'Foreign Governments Agencies',
  'International Organizations',
  'International Bodies',
  'General Government Units',
  'Domestic Statutory  Payments - District Assemblies Common Fund',
  'Ghana Educational Trust Fund',
  'Domestic Discretionary Payments-Transfers to MMDAs',
  'Central Government Allocation to MDAs',
  'Central Government Allocation to MMDAs',
  'Ghana Infrastructure Investment Fund(GIIF)',
  'School Feeding Program and Other Inflows',
  'GoG Compensation Transfers to MMDAs',
  'GoG Goods and Services Transfers to MMDAs',
  'GoG Asset Transfers to MMDAs',
  'Research and Innovation Facility',
  'Mineral Royalties - Transfers to MMDAs',
  'To other general government units -Capital',
  'Domestic Statutory  Payments - District Assemblies Common Fund',
  'MP\'s Capital Development Projects',
  'The Transfer of Sector-Specific Assets to MMDAs',
  'DDF Capacity Building Grants for Capital Expense',
  'Donor Support Capital Project',
  'Grant to Other SOEs',
  'Social benefits [GFS]',
  'Social Security Benefits in Cash',
  'Social Security Benefits in Cash',
  'National Health Insurance Scheme',
  'Social Assistance Benefits in Cash',
  'Social Assistance Benefits in Cash',
  'Exempt for Aged, Antenal and Under 5 Years',
  'Refund for Medical Expenses (Paupers/Disease Category)',
  'Social Assistance Benefits in Kind',
  'Social Assistance Benefits in Kind',
  'Employer Social Benefits in Cash',
  'Employer Social Benefits in Cash',
  'Workman  Compensation',
  'Staff Welfare Expenses',
  'Refund of Medical Expenses',
  'Employer Social Benefits in Kind',
  'Employer Social Benefits in Kind',
  'Other Expense',
  'Property Expense Other Than Interest',
  'Rent',
  'Miscellaneous Other Expense',
  'Current (Miscellaneous Other Expense) - General Expenses',
  'Insurance and Compensation',
  'Professional Fees',
  'Customs Duties',
  'Defence Attache',
  'United Nations Peace Keeping',
  'Court Expenses',
  'Awards and Rewards',
  'Donations',
  'Contributions',
  'Tuition Fees',
  'Scholarship/Awards',
  'Special Operations (COS)',
  'Special Operations (NSC)',
  'Special Operations (Peace Keeping)',
  'Special Operations (Docking of Ships)',
  'Refuse Lifting Expenses',
  'Civic Numbering/Street Naming',
  'Scholarship and Bursaries',
  'Grants to Employees',
  'Grants to Households',
  'National Awards',
  'Council Tax (Property Tax & Other Assembly Taxes)',
  'Direct Tax Refund',
  'Indirect Tax Refund',
  'Communication Service Tax Refund',
  'Resident Permit',
  'Accreditation Expenditure',
  'Dividend Paid By SOEs',
  'Judgement Debt Expense',
  'Foreign Financed Investment',
  'Project Grant Expense 2999002',
  'ASSET',
  'Non financial assets',
  'Fixed assets',
  'Buildings and Structures',
  'Residential Buildings',
  'Destitute Homes',
  'Bungalows/Flats',
  'Homes Of Aged',
  'Palace',
  'Barracks',
  'Hostels',
  'WIP - Buildings',
  'WIP - Dest. Homes',
  'WIP - Bungalows/Flat',
  'WIP-Home Of Aged',
  'WIP-Palace',
  'WIP-Barracks',
  'Residential Control Code',
  'Non-Residential Buildings',
  'Hospitals',
  'Clinics',
  'Day Care Centre',
  'Office Buildings',
  'School Buildings',
  'Slaughter House',
  'Health Centres',
  'Other Agricultural Structures',
  'Police Post',
  'Recreational Centres/Park',
  'Court Houses',
  'Libraries',
  'Restaurants',
  'Laboratories',
  'Research Facilities',
  'WIP - Hospitals',
  'WIP - Clinics',
  'WIP - Health Centres',
  'WIP - Day Care Centre',
  'WIP - Office Buildings',
  'WIP - School Buildings',
  'WIP - Slaughter House',
  'WIP-Recreational Centres/Park',
  'WIP - Police Post',
  'WIP- Libraries',
  'WIP - Laboratories',
  'WIP - Slaughter House',
  'Other structures',
  'Roads',
  'Cemeteries',
  'Toilets',
  'Markets',
  'Car/Lorry Park',
  'Bridges',
  'Road Signals',
  'Feeder Roads',
  'Urban Roads',
  'Highways',
  'Drainage',
  'Sports Stadium',
  'Workshop',
  'Railway Lines',
  'Border and Customs Control Points',
  'Warehouses and Storage Facilities',
  'Containers / Bins',
  'Perimeter Wall / Fence',
  'WIP - Roads',
  'WIP - Cemeteries',
  'WIP - Toilets',
  'WIP - Markets',
  'WIP - Car/Lorry Park',
  'WIP - Bridges',
  'WIP - Road Signals',
  'WIP-Feeder Roads',
  'WIP-Urban Roads',
  'WIP-Highways',
  'WIP-Drainage',
  'WIP-Sports Stadium',
  'WIP-Workshop',
  'WIP-Railway Lines',
  'WIP-Containers/Bins',
  'Other Structures Control Code',
  'Machinery and equipment',
  'Transport equipment',
  'Motor Vehicle',
  'Airplanes',
  'Trains',
  'Ships And Vessels',
  'Motor Bike, Bicycles Etc',
  'WIP - Trains',
  'WIP - Ships and Vessels',
  'Other Machinery And Equipment',
  'Agricultural Machinery',
  'Server (Computing)',
  'Networking and ICT Equipments',
  'Plant And Machinery',
  'Computers And Accessories',
  'Office Equipment',
  'Air Condition',
  'Communication Equipment',
  'Electrical Equipment',
  'Agriculture Facilities',
  'Security Equipment',
  'Housing Equipment',
  'Medical / Health Equipment',
  'Sports Equipment',
  'Laboratory Equipment-Medical Equipment',
  'Laboratory Equipment-Water Treatment',
  'Medical and Allied Equipment',
  'Music Instruments',
  'Photographic Equipment',
  'Recreational Centers',
  'WIP - Agricultural Machinery',
  'Other fixed assets',
  'Infrastructure Assets',
  'Electrical Networks',
  'Sewers',
  'Landscaping And Gardening',
  'Utilities Networks',
  'Runways',
  'Apron And Ramp Areas',
  'Furniture And Fittings',
  'Irrigation Systems',
  'Water Systems',
  'Heritage Assets',
  'Harbour And Landing Sites',
  'Sea Wall',
  'Fuel Tanks',
  'Water Tanks',
  'WIP - Electrical Networks',
  'WIP - Sewers',
  'WIP - Landscaping And Gardening',
  'WIP - Utilities Networks',
  'WIP - Runways',
  'WIP - Apron And Ramp Areas',
  'WIP - Furniture And Fittings',
  'WIP - Irrigation Systems',
  'WIP - Water Systems',
  'WIP-Harbour And Landing Sites',
  'WIP- Sea Wall',
  'Intangible Fixed Assets',
  'Software',
  'Computer Software',
  'Copyright/Patent/Trademark',
  'Printed Materials And Stationery',
  'Accessories',
  'Electrical Equipment',
  'Specialised Stock',
  'Medical Suppliers-Inventory',
  'Land',
  'Land',
  'Biological Assets',
  'Biological Assets _Animals',
  'Goat',
  'Sheep',
  'Pig',
  'Fowls',
  'Rabbit',
  'Grasscutter',
  'Cattle',
  'Plants',
  'Biological Assets-Tree Crops',
  'Root and Tuber',
  'Seeds',
  'Service Concession Arrangemant (PPP)',
  'Transport Infrastructure and Equipment',
  'Building Infrastructure  Assets',
  'ICT Infrastructure and Equipment',
  'Investment Property',
  'Investment Property_Land',
  'Land',
  'Investment Property_Building',
  'Office Building',
  'Non-Current Asset Held For Sale',
  'Non-Current Asset Held For Sale',
  'Office Equipment, Furniture and Fittings',
  'Biological Assets Held for Sale',
  'Leased Assets',
  'Leased Assets - Office Equipments',
  'Leased Assets - Office Building',
  'Leased Assets - Land',
  'Leased Assets - Plant and Equipment',
  'Leased Assets - -Motor Vehicle',
  'Depreciation Of Asset',
  'Investment Control Account',
] as const;
